### ISSUE TITLE
Ready for Pico 2?

### ISSUE THREAD

**Issue by dkyme** [PhrozenByte/pico-file-prefixes#1]
Dear @PhrozenByte,
I just played around with Pico Version 2.0.0-beta.3 but I couldn't figure out how to setup the Plugin with it.

At config.yml I tried:

```
PicoFilePrefixes.enabled: true
PicoFilePrefixes:
    recursiveDirs: '.'
    dirs:
```

for the configuration which works fine in the Version 1.0.6

$config['PicoFilePrefixes']['recursiveDirs'] = array('.');
$config['PicoFilePrefixes']['dirs'] = array();

I also tried to 'hardcode' the '.' instead of blog ... didn't work.
All prefixes are still there: 01.filename,md in the main folder 2018-05-01.event.md in the Eventfolder

You got any idea how I could get this feature done in Pico2?

Thanks in advance
